### ISSUE TITLE
Have you seen the Node proxy Census created?

### ISSUE THREAD

**Issue by ghost** [chadhuber/citysdk-node#3]
Hi @chadhuber ! Great foresight you have to put this together. We actually are creating a [Node proxy](https://github.com/uscensusbureau/citysdk/blob/master/src/api/README.md) ourselves... might you be interested?

**Comment by chadhuber** [comment]
Awesome!

**Comment by atsepkov** [comment]
Thank you so much for this project, I just now stumbled upon it after having used the other ones. I actually prefer this project to Node proxy because node proxy keeps throwing GeoJSON data at me, which I don't need, and I don't see a way to disable it like in this SDK. Moreover, really appreciate you updating the README.md to match the usage, I find it easier to follow than the official docs.

**Comment by chadhuber** [comment]
I really appreciate the kind words @atsepkov
